#!/usr/bin/env python3
"""
Quick guide to add sound effects to Protocol Outbreak
"""

print("="*70)
print("  Protocol Outbreak - Sound Effects Setup Guide")
print("="*70)
print()
print("🔊 QUICK SETUP - Generate Retro Sound Effects")
print()
print("Visit JSFXR (Web-based sound generator):")
print("   🌐 https://sfxr.me/")
print()
print("Generate these sounds:")
print()
print("1. SHOOT SOUND:")
print("   - Click 'Laser/Shoot' button")
print("   - Tweak settings if desired")
print("   - Click 'Export .wav'")
print("   - Save as: assets/sounds/shoot.wav")
print()
print("2. ENEMY HIT SOUND:")
print("   - Click 'Hit/Hurt' button")
print("   - Make it sharp and short")
print("   - Save as: assets/sounds/enemy_hit.wav")
print()
print("3. ENEMY DEATH SOUND:")
print("   - Click 'Explosion' button")
print("   - Make it satisfying!")
print("   - Save as: assets/sounds/enemy_death.wav")
print()
print("4. PLAYER HIT SOUND:")
print("   - Click 'Hit/Hurt' button")
print("   - Make it deeper/more painful")
print("   - Save as: assets/sounds/player_hit.wav")
print()
print("5. LEVEL COMPLETE SOUND:")
print("   - Click 'Pickup/Coin' button")
print("   - Make it cheerful/triumphant")
print("   - Save as: assets/sounds/level_complete.wav")
print()
print("="*70)
print()
print("📁 Save all files to:")
print("   /Users/jpozuna/Documents/Protocol-Outbreak/assets/sounds/")
print()
print("✅ Once files are added:")
print("   - Game will automatically use them")
print("   - No code changes needed")
print("   - Sounds will replace beep placeholders")
print()
print("="*70)
print()
print("🎵 BACKGROUND MUSIC: Already configured! ✅")
print("   Track: 'Cyborg Ninja' by Kevin MacLeod")
print("   Playing automatically when game starts")
print()
print("="*70)
